name: vems
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  shared_preferences:
  flutter_bloc: ^7.0.1
  #  firebase_core: ^0.4.5
  #  firebase_analytics: ^5.0.15
  #  location: ^3.0.2
  #  firebase_messaging: ^6.0.16
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  timeago: ^3.1.0
  cached_network_image: ^3.2.0
  #  file_picker: ^1.12.0
  url_launcher: ^6.0.17
  shimmer: ^2.0.0
  #  razorpay_flutter: ^1.2.1
  permission_handler: ^8.3.0
  #  location: ^3.0.2
  flutter_local_notifications: ^9.2.0
  #  path_provider: ^1.6.11
  get: ^4.6.1
  flutter_svg: ^1.0.0
  flutter_keyboard_visibility: ^5.1.0
  visibility_detector: ^0.2.2
  screen: ^0.0.5
  carousel_slider: ^4.0.0
  advance_pdf_viewer: ^2.0.1
  file_picker: ^4.3.1
  flutter_rating_bar: ^4.0.0
  #  flutter_markdown: ^0.6.2
  #  html2md: ^1.2.1
  # flutter_zoom_plugin: ^0.0.7
  adhara_socket_io: ^1.0.1+1
  google_sign_in: ^5.2.3
  device_info_plus: ^3.2.1
  fluttertoast: ^8.0.8
  html_editor:
  flutter_html: ^2.2.1
  sqflite: ^2.0.1
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  intl_utils: 2.6.0
dependency_overrides:
  intl: ^0.17.0
  wakelock: ^0.5.6
  webview_flutter: ^3.0.0
  flutter_svg: ^1.0.0
  provider: ^6.0.2
  image_picker: ^0.8.4+4
#  flutter_markdown: ^0.6.2
#  html2md: ^1.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/anim/

flutter_icons:
  android: "ic_launcher_round"
  ios: true
  image_path: "assets/icons/logo_round.png"


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800

#flutter_intl:
#  enabled: true
